### ISSUE TITLE
ReferenceError: location is not defined (node v4.4.1)

### ISSUE THREAD

**Issue by benno-huber** [Automattic/wpcom-oauth-cors#7]
Sorry, I'm quite new to node and wpcom package and for sure I'm doing something wrong.
But probably someone could have a look into my issue.

Trying to run example code from README with node version 4.4.1 following error is thrown:

  params.redirect_uri = opts.redirect || location.href.replace(/#.*$/, '');
                                         ^

ReferenceError: location is not defined
    at wpOAuth (C:\test\node_modules\wpcom-oauth-cors\index.js:47:42)
    at Object.<anonymous> (C:\test\wp-oauth.js:1:107)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by benno-huber** [comment]
wrong context for execution was selected; variable "location" only available inside browser context.
